#name, main, version and api are required
name: DisguiseMe
main: com.fcmcpe.disguiseme.DisguiseMePlugin
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1"
api: ["1.0.0"]

load: STARTUP
author: FunCraft Team
description: Rewrite DisguiseMe in Nukkit. Origin by Falk in https://github.com/Falkirks/DisguiseMe/ .
website: http://www.fcmcpe.com